version: '2'
services:
    postgres:
        build: ./postgres
        image: natan/banco_compose
        container_name: banco_compose
        ports:
            - "5434:5432"
    app:
        build: .
        image: natan/deskapp_compose
        container_name: deskapp_compose 
        links: 
            - "postgres:banco-loja"
    